//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB2_Register_Enums.h>

//-----------------------------------------------------------------------------
// Global VARIABLES
//-----------------------------------------------------------------------------
int LEDCOUNT = 0;

//-----------------------------------------------------------------------------
// Global CONSTANTS
//-----------------------------------------------------------------------------
SI_SBIT(MCU_LED1, SFR_P1, 3);// P1.3 MCU_LED1
SI_SBIT(MCU_LED2, SFR_P1, 4);// P1.4 MCU_LED2

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
{
    TMR2CN0_TF2H = 0; // Clear Timer2 interrupt flag
    if (LEDCOUNT == 10)
      {
        MCU_LED1 = ~MCU_LED1;
      }
    if (LEDCOUNT == 20)
      {
        MCU_LED1 = ~MCU_LED1;
        MCU_LED2 = ~MCU_LED2;
        LEDCOUNT = 0;
      }
    LEDCOUNT++;
}
